version: "3.8"

services:
  db:
    image: registry-1.docker.io/library/db:latest
    container_name: db_container
    hostname: db
    ports:
      - "8086:8086"
    environment:
      APP_PORT: 8086
      DB_URL: 192.168.122.1:5432
      KEYCLOAK_URL: http://192.168.122.1:8085
      LOGSTASH_URL: 192.168.122.1:12202
      BD_SERVICE_URL: http://192.168.122.1:8086
      CONSUL_URL: http://192.168.122.1:8500

# docker-compose up -d name