version: "3.8"

services:

  consul:
    image: consul:1.14.4
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8300:8300"
      - "8600:53/udp"

# docker-compose up -d name