version: "3.8"

services:
  crm:
    image: crm
    container_name: crm_container
    hostname: crm
    environment:
      HTTP_BIND_PORT: 8082
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
    ports:
      - "8082:8080"

  scheduler:
    image: scheduler
    container_name: scheduler_container
    hostname: scheduler
    environment:
      HTTP_BIND_PORT: 8082
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8089
    ports:
      - "8082:8089"

# docker-compose up -d name