version: "3.2"
services:
  postgres:
    container_name: postgres_container
    hostname: postgres
    image: postgres:14
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5431:5432"
    #networks:
    #  - host

  keycloakdc:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: keycloakdc
    hostname: keycloak
    #command: [ "-Djboss.http.port=8082" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_container
      DB_DATABASE: keycloak_db
      DB_USER: crm
      DB_PASSWORD: crm
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /keycloak/realm.json
    ports:
      - "8082:8080"
    #networks:
    #  - host
    #depends_on:
    #  - postgres
    #      KEYCLOAK_HTTP_PORT: 8089
    #      KEYCLOAK_HTTPS_PORT: "8443"
    #      KEYCLOAK_ALWAYS_HTTPS: "true"
    #volumes:

  crm:
    image: crm_/resources:1.0-SNAPSHOT
    container_name: crm_container
    hostname: crm
    environment:
      HTTP_BIND_PORT: 8082
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
    ports:
      - "8082:8080"

  scheduler:
    image: scheduler
    container_name: scheduler_container
    hostname: scheduler
    environment:
      HTTP_BIND_PORT: 8082
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
    ports:
      - "8082:8080"

# docker-compose up -d name