version: "2.2"
services:
  postgres:
    container_name: postgres_container
    hostname: postgres
    image: postgres:11
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    hostname: keycloak
    command: [ "-Djboss.http.port=8080" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_container
      DB_DATABASE: keycloak_db
      DB_USER: crm_
      DB_PASSWORD: crm_
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /keycloak/realm.json
    #      KEYCLOAK_HTTP_PORT: 8089
    #      KEYCLOAK_HTTPS_PORT: "8443"
    #      KEYCLOAK_ALWAYS_HTTPS: "true"
    #volumes:

  crm_:
    image: crm
    container_name: crm_container
    hostname: crm
    environment:
      HTTP_BIND_PORT: 8082
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
    ports:
      - "8082:8080"

# docker-compose up -d name