datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
- name: prometheus
  # <string, required> Sets the access mode, either
  # proxy or direct (Server or Browser in the UI).
  # Some data sources are incompatible with any setting
  # but proxy (Server).
  access: proxy
  # <string, required> Sets the data source type.
  type: prometheus
  # <string> Sets a custom UID to reference this
  # data source in other parts of the configuration.
  # If not specified, Grafana generates one.
  url: 'http://prometheus:9090'
  # <bool> Toggles whether the data source is pre-selected
  # for new panels. You can set only one default
  # data source per organization.
  isDefault: true
  # <bool> Allows users to edit data sources from the
  # Grafana UI.
  editable: true