datasources:
  # Устанавливает имя, которое вы используете для ссылки на
  # источник данных в панелях и запросах.
- name: prometheus
  # Устанавливает режим доступа либо
  # прокси или прямой (сервер или браузер в пользовательском интерфейсе).
  # Некоторые источники данных несовместимы ни с одной настройкой
  # но прокси (Сервер).
  access: proxy
  # Задает тип источника данных.
  type: prometheus
  # Устанавливает пользовательский UID для ссылки на этот
  # источник данных в других частях конфигурации.
  # Если не указано, Grafana создаст его.
  url: 'http://prometheus:9090'
  # Переключает, выбран ли источник данных заранее
  # для новых панелей. Вы можете установить только одно значение по умолчанию
  # источник данных для каждой организации.
  isDefault: true
  # Позволяет пользователям редактировать источники данных из
  # Интерфейс Графана.
  editable: true