version: "3.8"

services:
  postgres:
    container_name: postgres_container
    hostname: postgres
    image: postgres:14
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
#    networks:
#      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: keycloak
    hostname: keycloak
    command: ["--import-realm"]
    #restart: unless-stopped
    environment:
      #DB_VENDOR: POSTGRES
      #DB_ADDR: postgres_container
      #DB_DATABASE: keycloak_db
      #DB_USER: crm
      #DB_PASSWORD: crm
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

      #KEYCLOAK_ADMIN: admin
      #KEYCLOAK_ADMIN_PASSWORD: admin

      #KEYCLOAK_IMPORT: ./keycloak/realm.json
      #KEYCLOAK_FRONTEND_URL: http://192.168.1:8082/
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    #depends_on:
    #  - keycloak

    #networks:
#  keycloak:
#    driver: bridge

    #depends_on:
    #  - keycloak

    #      KEYCLOAK_HTTP_PORT: 8089
    #      KEYCLOAK_HTTPS_PORT: "8443"
    #      KEYCLOAK_ALWAYS_HTTPS: "true"
    #volumes:
