version: "3.8"

services:

  crm-service_1:
    image: registry-1.docker.io/library/crm:latest
    container_name: crm_container_1
    hostname: crm-service_1
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      HOST_URL: http://192.168.122.215
      KEYCLOAK_URL: http://192.168.122.1:8085
      LOGSTASH_URL: 192.168.122.1:12202
      BD_SERVICE_URL: http://192.168.122.1:8086
      CONSUL_URL: http://192.168.122.1:8500

  crm-service_2:
    image: registry-1.docker.io/library/crm:latest
    container_name: crm_container_2
    hostname: crm-service_2
    ports:
      - "8083:8083"
    environment:
      APP_PORT: 8083
      KEYCLOAK_URL: http://192.168.122.1:8085
      LOGSTASH_URL: 192.168.122.1:12202
      BD_SERVICE_URL: http://192.168.122.1:8086
      CONSUL_URL: http://192.168.122.1:8500

      # docker-compose up -d name