version: "3.8"

services:
  crm-1:
    image: registry-1.docker.io/library/crm:latest
    container_name: crm_container
    hostname: crm
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      DB_URL: 192.168.122.1:5432
      KEYCLOAK_URL: http://192.168.122.1:8085
      LOGSTASH_URL: 192.168.122.1:12202
      BD_SERVICE_URL: http://192.168.122.1:8086
      CONSUL_URL: http://192.168.122.1:8500

  crm-2:
    image: registry-1.docker.io/library/crm:latest
    container_name: crm_container
    hostname: crm
    ports:
      - "8083:8083"
    environment:
      APP_PORT: 8083
      DB_URL: 192.168.122.1:5432
      KEYCLOAK_URL: http://192.168.122.1:8085
      LOGSTASH_URL: 192.168.122.1:12202
      BD_SERVICE_URL: http://192.168.122.1:8086
      CONSUL_URL: http://192.168.122.1:8500

# docker-compose up -d name