global:
  scrape_interval: 15s
  evaluation_interval:  15s

#rule_files:
#  - alert.yal

scrape_configs:
  - job_name: prometheus
#    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: consul-metrics
    metrics_path: /q/metrics
    static_configs:
      - targets: ['localhost:8080']