version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DATABASE=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin